# Generated by Django 5.2.11 on 2026-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отдел"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Должность"
            ),
        ),
    ]
