# Generated by Django 5.2.11 on 2026-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_department_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО"
            ),
        ),
    ]
