# Generated by Django 5.2.11 on 2026-02-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("in_progress", "В работе"),
                    ("done", "Завершена"),
                    ("blocked", "Заблокирована"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
